# Generated by Django 6.0.5 on 2026-06-07 15:22

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "down_payment",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                ("tenor_months", models.PositiveIntegerField()),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[("due", "Due"), ("paid", "Paid"), ("overdue", "Overdue")],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="credit.credit",
                    ),
                ),
            ],
            options={
                "ordering": ["credit", "sequence"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["created_on"], name="credit_cred_created_0a3cc7_idx"),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(fields=["created_on"], name="credit_inst_created_ae3f37_idx"),
        ),
    ]
