# Generated by Django 6.0.5 on 2026-06-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold_cash", "Sold (cash)"),
                    ("ongoing_installment", "Installment"),
                    ("installment_paid", "Paid off"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
