# Generated by Django 6.0.5 on 2026-06-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("credit", "Sharia credit")], max_length=10
                    ),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("sold_on", models.DateField()),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                ("buyer_phone", models.CharField(blank=True, max_length=40)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_on", "-created_on"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["created_on"], name="sales_sale_created_930abd_idx")
                ],
            },
        ),
    ]
